apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  labels: 
    component: backstage-workloads
  annotations:
    github.com/project-slug: debsmita1/app-1
    backstage.io/kubernetes-id: janus-idp
    backstage.io/kubernetes-namespace: janus-idp
    janus-idp.io/tekton-enabled: 'true'
    #dev.azure.com/project-repo: my-project/my-repo
spec:
  type: service
  lifecycle: unknown
  owner: temp-d
