apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  labels: 
    component: backstage-workloads
  annotations:
    argocd/app-name: 'janus-idp'
    github.com/project-slug: janus-idp/backstage-showcase
    quay.io/repository-slug: janus-idp/backstage-showcase
    backstage.io/kubernetes-id: test-backstage
    #backstage.io/kubernetes-namespace: backstage-workshop
    #backstage.io/kubernetes-namespace: deb-test
    janus-idp.io/tekton-enabled: 'true'
    backstage.io/techdocs-ref: dir:.
    #dev.azure.com/project-repo: my-project/my-repo
    'jfrog-artifactory/image-name': 'test'
    nexus-repository-manager/docker.image-name: sonatype/nexus3
spec:
  type: service
  lifecycle: unknown
  owner: Debsmita Santra
